version: "3.7"
services:
  go-server:
    build:
      context: go
      dockerfile: Dockerfile
    expose:
      - "5555"
    volumes:
      - "./go:/code"

  ruby-server:
    build:
      context: ruby
      dockerfile: Dockerfile
    expose:
    - "5555"
    volumes:
    - "./ruby:/code"

  server-proxy:
    image: "envoyproxy/envoy:v1.14.4"
    volumes:
    - "./envoy:/etc/envoy"
    command: "envoy -c /etc/envoy/server.yaml"
    links:
    - "ruby-server"
    ports:
    - "8000:8000"
    - "8081:8081"

  ruby-client:
    build:
      context: ruby
      dockerfile: Dockerfile
    entrypoint: /code/client.rb
    volumes:
    - "./ruby:/code"

  jaeger:
    image: jaegertracing/all-in-one
    expose:
    - "14268"
    ports:
    - "16686:16686"
